name: Bug Report
description: Report a bug or issue
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for reporting a bug! Please fill out the form below to help us resolve the issue efficiently.**

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly summarize the issue in one or two sentences.
      placeholder: "The app crashes when clicking the save button."

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the issue, including any error messages or unexpected behavior.
      placeholder: "Steps to reproduce the issue: 1. Open the app 2. Click 'Save'..."

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How critical is the issue?
      options:
        - Critical
        - Major
        - Minor

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps necessary to reproduce the issue.
      placeholder: "1. Open the app 2. Click on the save button..."

  - type: input
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "The app should save the data without crashing."

  - type: input
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "The app crashes with an error message."

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description