name: Feature Request
description: Propose a new feature for the project
title: "[FEATURE] "
labels: ["feature request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for proposing a new feature! Please fill out the form below.**

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the feature you are requesting.
      placeholder: "Add dark mode support."

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Provide a detailed description of the new feature and why it is important.
      placeholder: "A dark mode feature would enhance user experience for those working in low-light environments."

  - type: textarea
    id: potential-use-cases
    attributes:
      label: Potential Use Cases
      description: Describe scenarios in which this feature would be useful.
      placeholder: "Developers who work late at night would benefit from a less glaring UI."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, links, or screenshots to support your request.
      placeholder: "Mockup design: [link to design]"
